In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 小数第３位まで表示
%precision 3

'%.3f'

In [5]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [7]:
data.dtype

dtype('int64')

In [8]:
print('次元数:', data.ndim)
print('要素数:', data.size)

次元数: 1
要素数: 10


In [9]:
data * 2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [15]:
sort_num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print('掛け算:', sort_num * np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))
print('累乗:', sort_num ** 2)
print('割り算:', sort_num / np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

掛け算: [10 18 24 28 30 30 28 24 18 10]
累乗: [  1   4   9  16  25  36  49  64  81 100]
割り算: [ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]


In [16]:
print('そのまま:', data)

data.sort()
print('ソート後:', data)

そのまま: [ 9  2  3  4 10  6  7  8  1  5]
ソート後: [ 1  2  3  4  5  6  7  8  9 10]


In [17]:
data[::-1].sort()
data

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [18]:
print('Min:', data.min())
print('Max:', data.max())
print('Sum:', data.sum())
print('Cum:', data.cumsum())
print('Ratio:', data.cumsum() / data.sum())

Min: 1
Max: 10
Sum: 55
Cum: [10 19 27 34 40 45 49 52 54 55]
Ratio: [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


In [2]:
import numpy.random as random

In [20]:
random.seed(0)

In [21]:
# 正規分布(平均0、分散１）の欄数を１０個発生
rnd_data = random.randn(10)

print('乱数10個の配列:', rnd_data)

乱数10個の配列: [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [25]:
# 抽出対象データ
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])

# ランダム抽出
# １０個抽出（重複あり、復元抽出）
print(random.choice(data, 10))
# 10個抽出（重複なし、非復元抽出)
print(random.choice(data, 10))

[4 9 4 6 9 3 4 1 2 4]
[ 4  4  8  9  2  5  5  9 10  8]


In [26]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
array1 = np.arange(9).reshape(3, 3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
# 1行目
array1[0, :]

array([0, 1, 2])

In [30]:
# 1列目
array1[:, 0]

array([0, 3, 6])

In [33]:
array2 = np.arange(9, 18).reshape(3, 3)
print(array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [34]:
np.dot(array1, array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [37]:
print(np.zeros((2, 3), dtype = np.int64))
print(np.ones((2, 3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [38]:
numbers = np.arange(1, 51)
total = 0

for i in numbers:
    total += i
print(total)

1275


In [4]:
random.seed(0)
rnd_data = random.randn(10)
print('最小値:', rnd_data.min())
print('最大値:', rnd_data.max())
print('合計:', rnd_data.sum())

最小値: -0.977277879876411
最大値: 2.240893199201458
合計: 7.380231707288347


In [12]:
m = np.ones((5, 5), dtype='i') * 3
print(m.dot(m))

[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]


In [16]:
# 線形代数用のライブラリ
import scipy.linalg as linalg

# 最適か計算（最小値）用の関数
from scipy.optimize import minimize_scalar

In [18]:
matrix = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])

# 行列式
print('行列式')
print(linalg.det(matrix))

行列式
-4.0


In [19]:
# 逆行列
print('逆行列')
print(linalg.inv(matrix))

逆行列
[[-0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [21]:
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
# 固有値と固有ベクトル
eig_value, eig_vector )= linalg.eig(matrix

print('固有値')
print(eig_value)
print('固有ベクトル')
print(eig_vector)

固有値
[-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル
[[-5.774e-01 -1.068e-16 -5.774e-01]
 [-5.774e-01  7.071e-01 -2.113e-01]
 [-5.774e-01 -7.071e-01  7.887e-01]]


In [24]:
# 関数の定義
def my_function(x):
    return (x ** 2 + 2 * x + 1)

In [30]:
# ニュートン法の読み込み
from scipy.optimize import newton

# 計算実行
print(newton(my_function, 0))

-0.9999999852953906


In [32]:
# 計算実行
print(minimize_scalar(my_function, method = 'Brent'))

 message: 
          Optimization terminated successfully;
          The returned value satisfies the termination criteria
          (using xtol = 1.48e-08 )
 success: True
     fun: 0.0
       x: -1.0000000000000002
     nit: 4
    nfev: 8


In [34]:
mat = np.array([[1, 2, 3], [1, 3, 2], [3, 1, 2]])
print(linglg.det(mat))

-12.000000000000002


In [35]:
# 逆行列、固有値、固有ベクトル
eig_value, eig_vector = linalg.eig(matrix)
print('逆行列:', linalg.inv(mat))
print('固有値:', eig_value)
print('固有ベクトル:', eig_vector)

逆行列: [[-0.333  0.083  0.417]
 [-0.333  0.583 -0.083]
 [ 0.667 -0.417 -0.083]]
固有値: [-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル: [[-5.774e-01 -1.068e-16 -5.774e-01]
 [-5.774e-01  7.071e-01 -2.113e-01]
 [-5.774e-01 -7.071e-01  7.887e-01]]


In [36]:
def func(x):
    return x ** 3 + 2 * x + 1

In [37]:
print(newton(func, 0))

-0.45339765151640365


In [38]:
import pandas as pd
from pandas import Series, DataFrame

In [39]:
# Series
sample_pandas_data = pd.Series([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
print(sample_pandas_data)

0     0
1    10
2    20
3    30
4    40
5    50
6    60
7    70
8    80
9    90
dtype: int64


In [40]:
# indexをアルファベットでつける
sample_pandas_index_data = pd.Series(
    [0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
    index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(sample_pandas_index_data)

a     0
b    10
c    20
d    30
e    40
f    50
g    60
h    70
i    80
j    90
dtype: int64


In [41]:
print('データの値:', sample_pandas_index_data.values)
print('インデックスの値:', sample_pandas_index_data.index)

データの値: [ 0 10 20 30 40 50 60 70 80 90]
インデックスの値: Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='str')


In [42]:
attri_data1 = {'ID':['100', '101', '102', '103', '104'],
               'City':['Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Tokyo'],
               'Birth_year':[1990, 1989, 1992, 1997, 1982],
               'Name':['Hiroshi', 'Akiko', 'Yuki', 'Satoru', 'Steve']}

attri_data_frame1 = DataFrame(attri_data1)

print(attri_data_frame1)

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve


In [43]:
attri_data_frame_index1 = DataFrame(attri_data1, index=['a', 'b', 'c', 'd', 'e'])
print(attri_data_frame_index1)

    ID      City  Birth_year     Name
a  100     Tokyo        1990  Hiroshi
b  101     Osaka        1989    Akiko
c  102     Kyoto        1992     Yuki
d  103  Hokkaido        1997   Satoru
e  104     Tokyo        1982    Steve


In [44]:
attri_data_frame_index1

,ID,City,Birth_year,Name
a,100,Tokyo,1990,Hiroshi
b,101,Osaka,1989,Akiko
c,102,Kyoto,1992,Yuki
d,103,Hokkaido,1997,Satoru
e,104,Tokyo,1982,Steve
